version: '3.8'
services:
  vpn:
    container_name: sdsu_vpn
    image: openconnect-proxy:latest
    privileged: true
    env_file:
      - .env.edu
    volumes:
      - ./hipreport-sdsu.sh:/etc/hipreport-sdsu.sh:ro
    ports:
      - "0.0.0.0:10080:8888"
      - "0.0.0.0:10090:8889"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    dns_opt:
      - ndots:0
    environment:
      - VPN_SPLIT=0
      - INTERNAL_IP4_DNS=8.8.8.8,8.8.4.4