version: '3.8'
services:
  vpn:
    container_name: sdsu_vpn
    image: openconnect-proxy:latest
    privileged: true
    env_file:
      - .env.edu
    volumes:
      - ./hipreport-sdsu.sh:/etc/hipreport-sdsu.sh:ro
      - ./fix-routes.sh:/usr/local/bin/fix-routes.sh:ro
    ports:
      - "0.0.0.0:10080:8888"
      - "0.0.0.0:10090:8889"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "/entrypoint.sh & sleep 30 && sh /usr/local/bin/fix-routes.sh; wait"



